
import {
    SiSass,
    SiNodedotjs,
    SiWordpress,
    SiTypescript,
    SiTailwindcss,
    SiBootstrap,
    SiFramer,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiNuxtdotjs,
    SiMongodb,
    SiPrisma,
    SiLaravel,
    SiGit,
    SiGithub,
    SiDigitalocean,
    SiFigma,
} from "react-icons/si";


export const LogosCarousel = [
    { name: "Bootstrap", icon: SiBootstrap, href: "https://getbootstrap.com/" },
    { name: "Digitalocean", icon: SiDigitalocean, href: "https://www.digitalocean.com/" },
    { name: "Framer Motion", icon: SiFramer, href: "https://www.framer.com/motion/" },
    { name: "Git", icon: SiGit, href: "https://git-scm.com/" },
    { name: "GitHub", icon: SiGithub, href: "https://github.com/" },
    { name: "Laravel", icon: SiLaravel, href: "https://laravel.com/" },
    { name: "MongoDB", icon: SiMongodb, href: "https://www.mongodb.com/" },
    { name: "Next.js", icon: SiNextdotjs, href: "https://nextjs.org/" },
    { name: "Node.js", icon: SiNodedotjs, href: "https://nodejs.org/" },
    { name: "Nuxt.js", icon: SiNuxtdotjs, href: "https://nuxt.com/" },
    { name: "Prisma", icon: SiPrisma, href: "https://www.prisma.io/" },
    { name: "React", icon: SiReact, href: "https://reactjs.org/" },
    { name: "Sass", icon: SiSass, href: "https://sass-lang.com/" },
    { name: "TailwindCSS", icon: SiTailwindcss, href: "https://tailwindcss.com/" },
    { name: "TypeScript", icon: SiTypescript, href: "https://www.typescriptlang.org/" },
    { name: "Vue.js", icon: SiVuedotjs, href: "https://vuejs.org/" },
    { name: "WordPress", icon: SiWordpress, href: "https://wordpress.org/" },
    { name: "Figma", icon: SiFigma, href: "https://www.figma.com/" },
];